### ISSUE TITLE
[Need help] fatal: tag 'v0.0.4' already exists

### ISSUE THREAD

**Issue by o0shojo0o** [AlCalzone/release-script#68]
I can not get any further .
I always get the following error message, although I no longer have a tag 'v0.0.4' in the repo. 
Am I missing something ? 
Release Script: 1.10.0
Git: https://github.com/o0shojo0o/ioBroker.matomo
Error: 
```
PS C:\Users\Dennis\Documents\GitHub\ioBroker.matomo> npm run release patch -- --all

> iobroker.matomo@0.0.3 release C:\Users\Dennis\Documents\GitHub\ioBroker.matomo
> release-script "patch" "--all"

git status is good - I can continue...
bumping version 0.0.3 to patch version 0.0.4

updating package.json from 0.0.3 to 0.0.4
updating README.md
updating io-package.json from 0.0.3 to 0.0.4
adding new news to io-package.json...
executing "npm install" ...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@parcel\watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

executing "git add -A -- ":(exclude).commitmessage"" ...
warning: LF will be replaced by CRLF in io-package.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
executing "git commit -F ".commitmessage"" ...
executing "git tag v0.0.4" ...
fatal: tag 'v0.0.4' already exists
Error: Command failed: git tag v0.0.4
fatal: tag 'v0.0.4' already exists

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at C:\Users\Dennis\Documents\GitHub\ioBroker.matomo\node_modules\@alcalzone\release-script\build\release.js:340:29
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dennis\Documents\GitHub\ioBroker.matomo\node_modules\@alcalzone\release-script\build\release.js:41:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 74 61 67 20 27 76 30 2e 30 2e 34 27 20 61 6c 72 65 61 64 79 20 65 78 69 73 74 73 0a>
  ],
  pid: 12980,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 74 61 67 20 27 76 30 2e 30 2e 34 27 20 61 6c 72 65 61 64 79 20 65 78 69 73 74 73 0a>
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.matomo@0.0.3 release: `release-script "patch" "--all"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.matomo@0.0.3 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dennis\AppData\Roaming\npm-cache\_logs\2021-05-28T07_00_02_638Z-debug.log
```

**Comment by AlCalzone** [comment]
Seems you have the tag locally. If something happens during the release, I usually use the following set of commands to clean up:
```
# Delete local tag:
git tag -d v0.0.4
# Delete tag from remote repo
git push --delete origin v0.0.4
```

**Comment by o0shojo0o** [comment]
Thanks, that helped, but unfortunately it still won't go through. 
Here is the new log: 
```
PS C:\Users\Dennis\Documents\GitHub\ioBroker.matomo> git tag -d v0.0.4
Deleted tag 'v0.0.4' (was 86e248f)
PS C:\Users\Dennis\Documents\GitHub\ioBroker.matomo> git push --delete origin v0.0.4
error: unable to delete 'v0.0.4': remote ref does not exist
error: failed to push some refs to 'https://github.com/o0shojo0o/ioBroker.matomo.git'
PS C:\Users\Dennis\Documents\GitHub\ioBroker.matomo> npm run release patch -- --all

> iobroker.matomo@0.0.3 release C:\Users\Dennis\Documents\GitHub\ioBroker.matomo
> release-script "patch" "--all"

git status is good - I can continue...
bumping version 0.0.3 to patch version 0.0.4

updating package.json from 0.0.3 to 0.0.4
updating README.md
updating io-package.json from 0.0.3 to 0.0.4
adding new news to io-package.json...
executing "npm install" ...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@parcel\watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

executing "git add -A -- ":(exclude).commitmessage"" ...
warning: LF will be replaced by CRLF in io-package.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
executing "git commit -F ".commitmessage"" ...
executing "git tag v0.0.4" ...
executing "git push" ...
To https://github.com/o0shojo0o/ioBroker.matomo.git
   1a2c23b..56023e7  main -> main
executing "git push --tags" ...
To https://github.com/o0shojo0o/ioBroker.matomo.git
 * [new tag]         v0.0.4 -> v0.0.4
 ! [remote rejected] v0.0.2 -> v0.0.2 (refusing to allow an OAuth App to create or update workflow `.github/workflows/test-and-release.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/o0shojo0o/ioBroker.matomo.git'
Error: Command failed: git push --tags
To https://github.com/o0shojo0o/ioBroker.matomo.git
 * [new tag]         v0.0.4 -> v0.0.4
 ! [remote rejected] v0.0.2 -> v0.0.2 (refusing to allow an OAuth App to create or update workflow `.github/workflows/test-and-release.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/o0shojo0o/ioBroker.matomo.git'

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at C:\Users\Dennis\Documents\GitHub\ioBroker.matomo\node_modules\@alcalzone\release-script\build\release.js:340:29
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dennis\Documents\GitHub\ioBroker.matomo\node_modules\@alcalzone\release-script\build\release.js:41:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 6f 20 68 74 74 70 73 3a 2f 2f 67 69 74 68 75 62 2e 63 6f 6d 2f 6f 30 73 68 6f 6a 6f 30 6f 2f 69 6f 42 72 6f 6b 65 72 2e 6d 61 74 6f 6d 6f 2e 67 69 ... 292 more bytes>
  ],
  pid: 21648,
  stdout: <Buffer >,
  stderr: <Buffer 54 6f 20 68 74 74 70 73 3a 2f 2f 67 69 74 68 75 62 2e 63 6f 6d 2f 6f 30 73 68 6f 6a 6f 30 6f 2f 69 6f 42 72 6f 6b 65 72 2e 6d 61 74 6f 6d 6f 2e 67 69 ... 292 more bytes>
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.matomo@0.0.3 release: `release-script "patch" "--all"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iobroker.matomo@0.0.3 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dennis\AppData\Roaming\npm-cache\_logs\2021-05-28T08_29_34_431Z-debug.log
```

**Comment by AlCalzone** [comment]
You seem to have another invalid tag (v0.0.2) locally. However I think it did go through:
The branch was pushed:
```
executing "git push" ...
To https://github.com/o0shojo0o/ioBroker.matomo.git
   1a2c23b..56023e7  main -> main
```
And the tag too:
```
executing "git push --tags" ...
To https://github.com/o0shojo0o/ioBroker.matomo.git
 * [new tag]         v0.0.4 -> v0.0.4
```
Here's your release building:
https://github.com/o0shojo0o/ioBroker.matomo/actions/runs/884945450

**Comment by o0shojo0o** [comment]
Thank you, that's it!
With `git tag -d v0.0.2` the problem was solved. :) 
So I realize that I still have some knowledge gaps in dealing with Git.
